using System;

namespace HyenaQuest;

[Serializable]
public enum STEAM_ACHIEVEMENTS : byte
{
	NONE = 0,
	ACHIEVEMENT_PIZZA = 1,
	ACHIEVEMENT_FORBIDDEN_PIZZA = 2,
	ACHIEVEMENT_MISSING_TEXTURE = 3,
	ACHIEVEMENT_OUT_OF_BOUNDS = 4,
	ACHIEVEMENT_SURFER = 5,
	ACHIEVEMENT_FORBIDDEN_LOVE = 6,
	ACHIEVEMENT_BRICKY = 7,
	ACHIEVEMENT_PRACTICE = 8,
	ACHIEVEMENT_UNIVERSE_LOAD = 9,
	ACHIEVEMENT_SPEEDRUN = 10,
	ACHIEVEMENT_URCHIN = 11,
	ACHIEVEMENT_MAP_APARTMENTS = 12,
	ACHIEVEMENT_MAP_TRAIN = 13,
	ACHIEVEMENT_MAP_CITY = 14,
	ACHIEVEMENT_MAP_FRACTURE = 15,
	ACHIEVEMENT_CHEAT_DEATH = 16,
	ACHIEVEMENT_SQUEAKY_CLEAN = 17,
	ACHIEVEMENT_PIZZA_TUNA = 18,
	ACHIEVEMENT_PIZZA_PEPPERONI = 19,
	ACHIEVEMENT_PIZZA_VEGGIE = 20,
	ACHIEVEMENT_STAN = 21,
	ACHIEVEMENT_MAP_TRENCHES = 22,
	ACHIEVEMENT_WELCOME = 23,
	ACHIEVEMENT_SCRAPPER = 100,
	ACHIEVEMENT_DELIVERY = 101,
	ACHIEVEMENT_ARRESTED = 102,
	ACHIEVEMENT_MASTER_MIND = 103,
	ACHIEVEMENT_DEATH = 104,
	ACHIEVEMENT_DEV = 230,
	ACHIEVEMENT_KOFI = 231
}
