using HyenaQuest;
using Unity.Collections;
using Unity.Netcode;
using UnityEngine;

namespace __GEN;

internal class NetworkVariableSerializationHelper
{
	[RuntimeInitializeOnLoadMethod]
	internal static void InitializeSerialization()
	{
		NetworkVariableSerializationTypedInitializers.InitializeSerializer_UnmanagedINetworkSerializable<Contract>();
		NetworkVariableSerializationTypedInitializers.InitializeEqualityChecker_UnmanagedIEquatable<Contract>();
		NetworkVariableSerializationTypedInitializers.InitializeSerializer_UnmanagedINetworkSerializable<Task>();
		NetworkVariableSerializationTypedInitializers.InitializeEqualityChecker_UnmanagedIEquatable<Task>();
		NetworkVariableSerializationTypedInitializers.InitializeSerializer_UnmanagedByMemcpy<bool>();
		NetworkVariableSerializationTypedInitializers.InitializeEqualityChecker_UnmanagedIEquatable<bool>();
		NetworkVariableSerializationTypedInitializers.InitializeSerializer_ManagedINetworkSerializable<Report>();
		NetworkVariableSerializationTypedInitializers.InitializeEqualityChecker_ManagedIEquatable<Report>();
		NetworkVariableSerializationTypedInitializers.InitializeSerializer_UnmanagedByMemcpy<INGAME_STATUS>();
		NetworkVariableSerializationTypedInitializers.InitializeEqualityChecker_UnmanagedValueEquals<INGAME_STATUS>();
		NetworkVariableSerializationTypedInitializers.InitializeSerializer_UnmanagedByMemcpy<byte>();
		NetworkVariableSerializationTypedInitializers.InitializeEqualityChecker_UnmanagedIEquatable<byte>();
		NetworkVariableSerializationTypedInitializers.InitializeSerializer_UnmanagedINetworkSerializable<EntryRenderSettings>();
		NetworkVariableSerializationTypedInitializers.InitializeEqualityChecker_UnmanagedIEquatable<EntryRenderSettings>();
		NetworkVariableSerializationTypedInitializers.InitializeSerializer_FixedString<FixedString128Bytes>();
		NetworkVariableSerializationTypedInitializers.InitializeEqualityChecker_UnmanagedIEquatable<FixedString128Bytes>();
		NetworkVariableSerializationTypedInitializers.InitializeSerializer_FixedString<FixedString64Bytes>();
		NetworkVariableSerializationTypedInitializers.InitializeEqualityChecker_UnmanagedIEquatable<FixedString64Bytes>();
		NetworkVariableSerializationTypedInitializers.InitializeSerializer_UnmanagedByMemcpy<PHONE_STATUS>();
		NetworkVariableSerializationTypedInitializers.InitializeEqualityChecker_UnmanagedValueEquals<PHONE_STATUS>();
		NetworkVariableSerializationTypedInitializers.InitializeSerializer_UnmanagedByMemcpy<SaveMODE>();
		NetworkVariableSerializationTypedInitializers.InitializeEqualityChecker_UnmanagedValueEquals<SaveMODE>();
		NetworkVariableSerializationTypedInitializers.InitializeSerializer_UnmanagedByMemcpy<float>();
		NetworkVariableSerializationTypedInitializers.InitializeEqualityChecker_UnmanagedIEquatable<float>();
		NetworkVariableSerializationTypedInitializers.InitializeSerializer_UnmanagedByMemcpy<TRANSFER_STATUS>();
		NetworkVariableSerializationTypedInitializers.InitializeEqualityChecker_UnmanagedValueEquals<TRANSFER_STATUS>();
		NetworkVariableSerializationTypedInitializers.InitializeSerializer_UnmanagedINetworkSerializable<GLASS_HEALTH>();
		NetworkVariableSerializationTypedInitializers.InitializeEqualityChecker_UnmanagedIEquatable<GLASS_HEALTH>();
		NetworkVariableSerializationTypedInitializers.InitializeSerializer_UnmanagedByMemcpy<LOCK_TYPE>();
		NetworkVariableSerializationTypedInitializers.InitializeEqualityChecker_UnmanagedValueEquals<LOCK_TYPE>();
		NetworkVariableSerializationTypedInitializers.InitializeSerializer_UnmanagedINetworkSerializable<NetworkBehaviourReference>();
		NetworkVariableSerializationTypedInitializers.InitializeEqualityChecker_UnmanagedIEquatable<NetworkBehaviourReference>();
		NetworkVariableSerializationTypedInitializers.InitializeSerializer_FixedString<FixedString4096Bytes>();
		NetworkVariableSerializationTypedInitializers.InitializeEqualityChecker_UnmanagedIEquatable<FixedString4096Bytes>();
		NetworkVariableSerializationTypedInitializers.InitializeSerializer_UnmanagedByMemcpy<PlayerAction>();
		NetworkVariableSerializationTypedInitializers.InitializeEqualityChecker_UnmanagedValueEquals<PlayerAction>();
		NetworkVariableSerializationTypedInitializers.InitializeSerializer_UnmanagedINetworkSerializable<CurseNetwork>();
		NetworkVariableSerializationTypedInitializers.InitializeEqualityChecker_UnmanagedIEquatable<CurseNetwork>();
		NetworkVariableSerializationTypedInitializers.InitializeSerializer_UnmanagedINetworkSerializable<HEALTH>();
		NetworkVariableSerializationTypedInitializers.InitializeEqualityChecker_UnmanagedIEquatable<HEALTH>();
		NetworkVariableSerializationTypedInitializers.InitializeSerializer_UnmanagedByMemcpy<Vector3>();
		NetworkVariableSerializationTypedInitializers.InitializeEqualityChecker_UnmanagedIEquatable<Vector3>();
		NetworkVariableSerializationTypedInitializers.InitializeSerializer_ManagedINetworkSerializable<PortalOverride>();
		NetworkVariableSerializationTypedInitializers.InitializeEqualityChecker_ManagedIEquatable<PortalOverride>();
	}
}
